# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The title of -ReLU_rcpp-
#'
#' Here is a brief description
#'
#' @param a Numeric matrix.
#'
#' @details Computes the ReLU function value of each element of matrix \code{a}.
#' @return A matrix.
#' @examples
#' mat <- matrix(1:9,3,3)
#' ReLU_rcpp(mat)
#'
#' @export
ReLU_rcpp <- function(a) {
    .Call(`_BackPropNN_ReLU_rcpp`, a)
}

#' The title of -back_propagation_training_rcpp-
#'
#' Here is a brief description
#'
#' @param i Numeric scalar. Number of input nodes.
#' @param h Numeric scalar. Number of hidden nodes.
#' @param o Numeric scalar. Number of output nodes.
#' @param learning_rate Numeric scalar. Learning rate of the algorithm.
#' @param activation_func Character (either "sigmoid" or "ReLU").
#' @param data R data frame with X columns and Y labels.
#'
#' @details Computes the weight and bias matrices for the nodes of the neural network with \code{i} # of input nodes, \code{h} # of hidden nodes, and \code{o} # of output nodes.
#' @return A list of weight and bias matrices.
#' @examples
#' set.seed(100)
#' data <- data.frame(X1 = 1:100, X2 = 2:101, Y = sample(c(0,1), 100, replace=TRUE))
#' data_as_matrix <- as.matrix(data)
#' nn_model_rcpp <- back_propagation_training_rcpp(i=2, h=2, o=1, learning_rate=0.01,
#' activation_func="sigmoid", data=data_as_matrix)
#'
#' @export
back_propagation_training_rcpp <- function(i, h, o, learning_rate, activation_func, data) {
    .Call(`_BackPropNN_back_propagation_training_rcpp`, i, h, o, learning_rate, activation_func, data)
}

#' The title of -derivative_ReLU_rcpp-
#'
#' Here is a brief description
#'
#' @param a Numeric matrix.
#'
#' @details Computes the derivative of ReLU function value of each element of matrix \code{a}.
#' @return A matrix.
#' @examples
#' mat <- matrix(1:9,3,3)
#' derivative_ReLU_rcpp(mat)
#'
#' @export
derivative_ReLU_rcpp <- function(a) {
    .Call(`_BackPropNN_derivative_ReLU_rcpp`, a)
}

#' The title of -derivative_sigmoid_rcpp-
#'
#' Here is a brief description
#'
#' @param a Numeric matrix.
#'
#' @details Computes the derivative of sigmoid function value of each element of matrix \code{a}.
#' @return A matrix.
#' @examples
#' mat <- matrix(1:9,3,3)
#' derivative_sigmoid_rcpp(mat)
#'
#' @export
derivative_sigmoid_rcpp <- function(a) {
    .Call(`_BackPropNN_derivative_sigmoid_rcpp`, a)
}

#' The title of -feed_forward_rcpp-
#'
#' Here is a brief description
#'
#' @param data R data frame with X columns and Y labels.
#' @param nn_model A list of weight and bias matrices along with other information about fitted nn model.
#'
#' @details Computes the predicted value of the X columns of \code{data}.
#' @return A vector.
#' @examples
#' data <- data.frame(X1 = 1:10, X2 = 2:11, Y = sample(c(0,1), 10, replace=TRUE))
#' data_as_matrix <- as.matrix(data)
#' nn_model_rcpp <- back_propagation_training_rcpp(i=2, h=2, o=1, learning_rate=0.01,
#' activation_func="sigmoid", data=data_as_matrix)
#' feed_forward_rcpp(data, nn_model_rcpp)
#'
#' @export
feed_forward_rcpp <- function(data, nn_model) {
    .Call(`_BackPropNN_feed_forward_rcpp`, data, nn_model)
}

#' The title of -sigmoid_rcpp-
#'
#' Here is a brief description
#'
#' @param a Numeric matrix.
#'
#' @details Computes the sigmoid function value of each element of matrix \code{a}.
#' @return A matrix.
#' @examples
#' mat <- matrix(1:9,3,3)
#' sigmoid_rcpp(mat)
#'
#' @export
#' @useDynLib BackPropNN, .registration=TRUE
#' @importFrom Rcpp sourceCpp
sigmoid_rcpp <- function(a) {
    .Call(`_BackPropNN_sigmoid_rcpp`, a)
}

